# -*- mode: ruby -*-
# vi: set ft=ruby :
#

NODES = 3
DISKS = 8

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider :libvirt do |v,override|
        override.vm.box = "centos/7"
        override.vm.synced_folder '.', '/home/vagrant/sync', disabled: true
        # change cpu mode to passthrough as workaround, refer bugs:
        #https://bugzilla.redhat.com/show_bug.cgi?id=1467599
        #https://bugzilla.redhat.com/show_bug.cgi?id=1386223#c10
        #vagrant-libvirt/vagrant-libvirt#667
        v.cpu_mode = 'host-passthrough'
    end

    # Make the glusterfs cluster, each with DISKS number of drives
    (0..NODES-1).each do |i|
        config.vm.define "glusterd2#{i}" do |glusterd2|
            glusterd2.vm.hostname = "glusterd2#{i}"
            glusterd2.vm.network :private_network, ip: "192.168.10.10#{i}"
            (0..DISKS-1).each do |d|
                glusterd2.vm.provider :virtualbox do |vb|
                    vb.customize [ "createhd", "--filename", "disk-#{i}-#{d}.vdi", "--size", 500*1024 ]
                    vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 3+d, "--device", 0, "--type", "hdd", "--medium", "disk-#{i}-#{d}.vdi" ]
                    vb.memory = 1024
                    vb.cpus = 2
                end
                driverletters = ('b'..'z').to_a
                glusterd2.vm.provider :libvirt do  |lv|
                    lv.storage :file, :device => "vd#{driverletters[d]}", :path => "glusterd2-#{i}-#{d}.disk", :size => '500G'
                    lv.memory = 1024
                    lv.cpus =2
                end
            end

            if i == (NODES-1)
                # View the documentation for the provider you're using for more
                # information on available options.
                glusterd2.vm.provision :ansible do |ansible|
                    ansible.limit = "all"
                    ansible.playbook = "site.yml"
                    ansible.groups = {
                        "gluster" => (0..NODES-1).map {|j| "glusterd2#{j}"},
                    }

                end
            end
        end
    end
end

